runtime: nodejs18
env: flex
service: travel-expense-server

env_variables:
  DATABASE_URL: 'postgres://postgres:lael0laeq12@34.143.187.87:5432/travel_expense'
  PORT: 3000
  SECRET_KEY: 'getOutOfHereBtch'
